# Generated by Django 3.1.7 on 2021-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(max_length=100)),
                ('link2', models.CharField(max_length=100)),
                ('messages', models.ManyToManyField(to='message.M')),
            ],
        ),
    ]
