# Generated by Django 3.1.7 on 2021-10-16 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20211016_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
